name: Sydney Small Business Advisory Hub
favicon: null
layout_spectrum: 0.91286
typography_spectrum: 0.60321
title: Sydney Small Business Advisory Hub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75c7ef'
    - '#b0dbf4'
    - '#adaeb1'
    - '#6d6e70'
  brandStrength: 0.5730195792857558
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
