name: Sydney Small Business Advisory Hub
favicon: null
layout_spectrum: 0.94814
typography_spectrum: 0.82318
title: Sydney Small Business Advisory Hub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#555555'
    - '#dc4b36'
    - '#8d8d8d'
    - '#5ab5da'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
